### ISSUE TITLE
Page is cacheable

### ISSUE THREAD

**Issue by chadparry** [colmmacc/neverssl.com#4]
I love your site, and I use it at airports and hotels all the time. But sometimes it doesn't work because of browser caching. You say on the ["changes"](http://neverssl.com/changes) page that your intention is that "caching is aggressively disabled for that page". I don't see any of the headers that would normally help with cache-busting, though. I think they need to be restored for cache-busting to work.

As an example, here are the headers that I received in a recent test:

```
$ curl -sD - neverssl.com -o /dev/null
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 2536
Connection: keep-alive
Date: Mon, 15 Oct 2018 00:40:41 GMT
Last-Modified: Thu, 14 Jun 2018 00:16:40 GMT
ETag: "e8bb9152091d61caa9d69fed8c4aebc6"
Accept-Ranges: bytes
Server: AmazonS3
Vary: Accept-Encoding
Age: 7544
X-Cache: Hit from cloudfront
Via: 1.1 6eadd6c6c5a53c34c6fce458c34cd790.cloudfront.net (CloudFront)
X-Amz-Cf-Id: n0t3hLyn1Qh8vaPhsO7uAsMmUWLpjo5y_aUnK2oX26gDfDpftqb9Gw==

$
```

Can I please recommend that you add these HTTP headers to your page?

```
Cache-Control: no-store, must-revalidate
Pragma: no-cache
Expires: 0
```

Thanks again for your SSS.

**Comment by colmmacc** [comment]
try now! neverssl.com has been updated to include cache busting.
